name: Build/ios

on:
  push:
    branches:
      - "ios-ci"
      - master
    tags:
      - '*'
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1


      - name: Install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Build
        shell: bash
        run: |
          npm install -g @quasar/cli
          npm install -g cordova
          npm install
          quasar build -m ios
          ls -lah dist
          ls -lah dist/cordova
          find dist/cordova


      - uses: actions/upload-artifact@v2
        with:
          name: dadadash-app.apk
          path: dist/cordova/ios/DadaDash.app


      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            dist/cordova/ios/DadaDash.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
